[project]
name = "llama-deploy-chat-ui"
version = "0.1.0"
description = "Using LlamaDeploy with Chat UI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
]