[project]
name = "llama-deploy-workflows"
version = "0.1.0"
description = "Using LlamaDeploy with Workflow"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llama-deploy",
]

[tool.uv.sources]
llama-deploy = { git = "https://github.com/run-llama/llama_deploy" }
