packages:
  - "apps/*"
  - "packages/*"
  - "examples/**"
  - '!examples/llamadeploy-workflow/ui'  # UI will be built separately by llama-deploy server
  - '!examples/llamadeploy-chat/ui'  # UI will be built separately by llama-deploy server
  - "docs"
