packages:
  - "apps/*"
  - "packages/*"
  - "examples/**"
  - "docs"

  # UI will be built separately by llama-deploy server
  - "!examples/llamadeploy/workflow/ui"
  - "!examples/llamadeploy/chat/ui"
  - "!examples/llamadeploy/with-tsserver/ui"
